from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Barcode_Scanner(object):
    def setupUi(self, Barcode_Scanner):
        Barcode_Scanner.setObjectName("Barcode_Scanner")
        Barcode_Scanner.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(Barcode_Scanner)
        self.centralwidget.setObjectName("centralwidget")
        self.main_frame = QtWidgets.QFrame(self.centralwidget)
        self.main_frame.setGeometry(QtCore.QRect(0, 0, 791, 550))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        self.main_frame.setFont(font)
        self.main_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_frame.setObjectName("main_frame")
        self.Selection_buttons = QtWidgets.QFrame(self.main_frame)
        self.Selection_buttons.setGeometry(QtCore.QRect(120, 180, 611, 351))
        self.Selection_buttons.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Selection_buttons.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Selection_buttons.setObjectName("Selection_buttons")
        self.tab = QtWidgets.QTabWidget(self.Selection_buttons)
        self.tab.setGeometry(QtCore.QRect(30, 20, 541, 271))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(10)
        self.tab.setFont(font)
        self.tab.setObjectName("tab")
        self.Image = QtWidgets.QWidget()
        self.Image.setObjectName("Image")
        self.ok_button = QtWidgets.QDialogButtonBox(self.Image)
        self.ok_button.setGeometry(QtCore.QRect(160, 150, 193, 28))
        self.ok_button.setStandardButtons(QtWidgets.QDialogButtonBox.Ok|QtWidgets.QDialogButtonBox.Reset)
        self.ok_button.setCenterButtons(False)
        self.ok_button.setObjectName("ok_button")
        self.widget = QtWidgets.QWidget(self.Image)
        self.widget.setGeometry(QtCore.QRect(20, 60, 491, 29))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Address_bar = QtWidgets.QLineEdit(self.widget)
        self.Address_bar.setObjectName("Address_bar")
        self.horizontalLayout.addWidget(self.Address_bar)
        self.browser = QtWidgets.QToolButton(self.widget)
        self.browser.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.browser.setObjectName("browser")
        self.horizontalLayout.addWidget(self.browser)
        self.tab.addTab(self.Image, "")
        self.Webcam = QtWidgets.QWidget()
        self.Webcam.setObjectName("Webcam")
        self.open_cam_button = QtWidgets.QPushButton(self.Webcam)
        self.open_cam_button.setGeometry(QtCore.QRect(120, 40, 291, 151))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.open_cam_button.setFont(font)
        self.open_cam_button.setObjectName("open_cam_button")
        self.tab.addTab(self.Webcam, "")
        self.text_barcode_scanner = QtWidgets.QFrame(self.main_frame)
        self.text_barcode_scanner.setGeometry(QtCore.QRect(150, 80, 531, 91))
        self.text_barcode_scanner.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.text_barcode_scanner.setFrameShadow(QtWidgets.QFrame.Raised)
        self.text_barcode_scanner.setObjectName("text_barcode_scanner")
        self.label_barcode_scanner = QtWidgets.QLabel(self.text_barcode_scanner)
        self.label_barcode_scanner.setGeometry(QtCore.QRect(40, 5, 481, 81))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(36)
        font.setUnderline(False)
        self.label_barcode_scanner.setFont(font)
        self.label_barcode_scanner.setObjectName("label_barcode_scanner")
        Barcode_Scanner.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Barcode_Scanner)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        Barcode_Scanner.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Barcode_Scanner)
        self.statusbar.setObjectName("statusbar")
        Barcode_Scanner.setStatusBar(self.statusbar)
        self.actionAdd_image = QtWidgets.QAction(Barcode_Scanner)
        self.actionAdd_image.setObjectName("actionAdd_image")
        self.actionOpen_Web_Cam = QtWidgets.QAction(Barcode_Scanner)
        self.actionOpen_Web_Cam.setObjectName("actionOpen_Web_Cam")
        self.actionExit = QtWidgets.QAction(Barcode_Scanner)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionAdd_image)
        self.menuFile.addAction(self.actionOpen_Web_Cam)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(Barcode_Scanner)
        self.tab.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Barcode_Scanner)

    def retranslateUi(self, Barcode_Scanner):
        _translate = QtCore.QCoreApplication.translate
        Barcode_Scanner.setWindowTitle(_translate("Barcode_Scanner", "Barcode Scanner"))
        self.browser.setText(_translate("Barcode_Scanner", "..."))
        self.tab.setTabText(self.tab.indexOf(self.Image), _translate("Barcode_Scanner", "Image"))
        self.open_cam_button.setText(_translate("Barcode_Scanner", "Open Camera"))
        self.tab.setTabText(self.tab.indexOf(self.Webcam), _translate("Barcode_Scanner", "Webcam"))
        self.label_barcode_scanner.setText(_translate("Barcode_Scanner", "Barcode Scanner"))
        self.menuFile.setTitle(_translate("Barcode_Scanner", "File"))
        self.actionAdd_image.setText(_translate("Barcode_Scanner", "Add Image"))
        self.actionOpen_Web_Cam.setText(_translate("Barcode_Scanner", "Open Web Cam"))
        self.actionExit.setText(_translate("Barcode_Scanner", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Barcode_Scanner = QtWidgets.QMainWindow()
    ui = Ui_Barcode_Scanner()
    ui.setupUi(Barcode_Scanner)
    Barcode_Scanner.show()
    sys.exit(app.exec_())
